config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'plays#home'
  get 'plays/home'
  get 'plays/game'
  post 'create_play_images', to: 'plays#create_play_images'
  post 'plays', to: 'plays#create'
end

app/models/application_record.rb
# frozen_string_literal: true

# app/models/appliation_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play.rb
# frozen_string_literal: true

# app/models/play.rb
class Play < ApplicationRecord
end

app/models/play_image.rb
# frozen_string_literal: true

# app/models/play_image.rb
class PlayImage < ApplicationRecord
  has_many_attached :image
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
# frozen_string_literal: true

# app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def home
    @play_images = PlayImage.new
  end

  def create
    @play = Play.new(play_params)
    if @play.save
      render json: @play
    else
      render json: { error: 'something went wrong!' }
    end
  end

  def game
    images = PlayImage.all
                      .map { |play| play.image.attachments }
                      .flatten
                      .collect { |e| url_for(e).to_s }
    @random_images = images.shuffle.sample(rand(5..10))
    @plays = Play.all
  end

  def create_play_images
    @play_images = PlayImage.new(play_image_params)
    @play_images.save
    redirect_to plays_home_path
  end

  private

  def play_params
    params.require(:play).permit(:timer_count, :image_url)
  end

  def play_image_params
    params.require(:play_image).permit(image: [])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CounterGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application"  %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plays/game.html.erb
<%= link_to "Home", plays_home_path %>
<h1 id="timer"></h1>
<img src="" id="image" style="height: 100px">

<br><br>
<button onclick="postPlays()">Click me</button>
<br><br><br><br>

<table id="plays" data-images='<%= raw @random_images.to_json %>'>
<%= tag("div", id: "random-images",  data: @random_images) %>
  <tr>
    <th>Timer count</th>
    <th>Image</th>
  </tr>
  <% @plays.each do |play| %>
    <tr>
      <td><%= play.timer_count %></td>
      <td><img src="<%= play.image_url %>" style='height: 50px'></td>
    </tr>
  <% end %>
</table>

app/views/plays/home.html.erb
<%= link_to "Game", plays_game_path %><br>
<h2>Upload Images</h2>
<%= form_for @play_images, url: { controller: 'plays', action: 'create_play_images'} do |f| %>
  <fieldset>
    <legend>Upload Images</legend>
    <label>Choose Image files</label>
    <%= f.file_field  :image, multiple: true, id: 'file-field' %><br>
    <%= f.submit 'Upload', id: 'upload-button'%>
  </fieldset>
<% end %>